version: 1.0.0.{build}

skip_commits:
  message: /.*/
skip_branch_with_pr: true
skip_tags: true
skip_non_tags: true

os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1
  GENERATOR: "\"NMake Makefiles\""
  DEPS_MODE: internal

  matrix:
#    - BUILD_PLATFORM: clang
#      MSVC_RUNTIME_TYPE:
#      GENERATOR: "\"Unix Makefiles\""
#      DEPS_MODE: internal
#      EXTRA_CMAKE_ARGS: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_MAKE_PROGRAM=mingw32-make.exe -DCMAKE_VERBOSE_MAKEFILE=ON -DJINJA2CPP_STRICT_WARNINGS=OFF
    - BUILD_PLATFORM: MinGW7
      MSVC_RUNTIME_TYPE:
      GENERATOR: "\"Unix Makefiles\""
      DEPS_MODE: internal
      EXTRA_CMAKE_ARGS: -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++.exe -DCMAKE_MAKE_PROGRAM=mingw32-make.exe -DCMAKE_VERBOSE_MAKEFILE=ON -DJINJA2CPP_STRICT_WARNINGS=OFF
    - BUILD_PLATFORM: MinGW8
      MSVC_RUNTIME_TYPE:
      GENERATOR: "\"Unix Makefiles\""
      DEPS_MODE: internal
      EXTRA_CMAKE_ARGS: -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++.exe -DCMAKE_MAKE_PROGRAM=mingw32-make.exe  -DCMAKE_VERBOSE_MAKEFILE=ON -DJINJA2CPP_STRICT_WARNINGS=OFF
    - BUILD_PLATFORM: x64
      MSVC_RUNTIME_TYPE: /MD
    - BUILD_PLATFORM: x64
      MSVC_RUNTIME_TYPE: /MT
    - BUILD_PLATFORM: x64
      MSVC_RUNTIME_TYPE:
    - BUILD_PLATFORM: x86
      MSVC_RUNTIME_TYPE: /MD
    - BUILD_PLATFORM: x86
      MSVC_RUNTIME_TYPE: /MT
    - BUILD_PLATFORM: x86
      MSVC_RUNTIME_TYPE:

matrix:
  fast_finish: false
  exclude:
    - os: Visual Studio 2015
      BUILD_PLATFORM: MinGW7
    - os: Visual Studio 2015
      BUILD_PLATFORM: MinGW8
    - os: Visual Studio 2015
      BUILD_PLATFORM: clang
    - os: Visual Studio 2017
      BUILD_PLATFORM: x86
    - os: Visual Studio 2017
      BUILD_PLATFORM: x64
    - platform: Win32
      BUILD_PLATFORM: x64
    - platform: Win32
      BUILD_PLATFORM: MinGW7
    - platform: Win32
      BUILD_PLATFORM: MinGW8
    - platform: Win32
      BUILD_PLATFORM: clang
    - platform: x64
      BUILD_PLATFORM: x86
    

init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%BUILD_PLATFORM%"=="MinGW7" set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%BUILD_PLATFORM%"=="MinGW8" set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" if "%BUILD_PLATFORM%"=="clang" set PATH=%BOOST_ROOT%\lib64-msvc-14.1;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;C:\Libraries\llvm-5.0.0\bin;%PATH% && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%BUILD_PLATFORM%"=="x86" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%BUILD_PLATFORM%"=="x86" set PATH=%BOOST_ROOT%\lib32-msvc-14.0;%PATH%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%BUILD_PLATFORM%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if "%BUILD_PLATFORM%"=="x64" set PATH=%BOOST_ROOT%\lib64-msvc-14.0;%PATH%

build_script:
  - mkdir -p build && cd build
  - cmake .. -G %GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% -DJINJA2CPP_MSVC_RUNTIME_TYPE=%MSVC_RUNTIME_TYPE% -DJINJA2CPP_DEPS_MODE=%DEPS_MODE% %EXTRA_CMAKE_ARGS%
  - cmake --build . --target all --config %configuration%

test_script:
  - ctest -C %configuration% -V
